# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('parentId', models.IntegerField()),
                ('orderBy', models.IntegerField()),
                ('thumbnailUrl', models.URLField()),
                ('originalImageUrl', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('productCount', models.IntegerField()),
                ('_description', models.TextField(blank=True, db_column='description')),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('combinationNumber', models.IntegerField()),
                ('sku', models.CharField(max_length=255)),
                ('smallThumbnailUrl', models.URLField()),
                ('thumbnailUrl', models.URLField()),
                ('imageUrl', models.URLField()),
                ('originalImageUrl', models.URLField()),
                ('quantity', models.IntegerField()),
                ('unlimited', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=20)),
                ('warningLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sku', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unlimited', models.BooleanField()),
                ('inStock', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('priceInProductList', models.DecimalField(decimal_places=2, max_digits=20)),
                ('compareToPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('isShippingRequired', models.BooleanField()),
                ('weight', models.DecimalField(decimal_places=5, max_digits=20)),
                ('url', models.URLField()),
                ('createTimestamp', models.CharField(max_length=200)),
                ('updateTimestamp', models.CharField(max_length=200)),
                ('productClassId', models.IntegerField()),
                ('enabled', models.BooleanField()),
                ('warningLimit', models.IntegerField()),
                ('fixedShippingRateOnly', models.BooleanField()),
                ('fixedShippingRate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('defaultCombinationId', models.IntegerField()),
                ('thumbnailUrl', models.URLField()),
                ('imageUrl', models.URLField()),
                ('smallThumbnailUrl', models.URLField()),
                ('originalImageUrl', models.URLField()),
                ('_description', models.TextField(blank=True, db_column='description')),
                ('defaultCategoryId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('show', models.CharField(max_length=255)),
                ('parentProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.IntegerField()),
                ('parentProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCombinationOptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('defaultChoice', models.IntegerField()),
                ('required', models.BooleanField()),
                ('parentCombination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.Combination')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCombinationWholesalePricesArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('parentProductCombination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.Combination')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFavoriteStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('displayCount', models.CharField(max_length=30)),
                ('parentProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('_description', models.TextField(blank=True, db_column='description')),
                ('size', models.IntegerField()),
                ('adminUrl', models.URLField()),
                ('parentProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('alt', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('thumbnail', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('imageUrl', models.URLField()),
                ('orderBy', models.IntegerField()),
                ('parentProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('priceModifier', models.DecimalField(decimal_places=2, max_digits=20)),
                ('priceModifierType', models.CharField(max_length=40)),
                ('parentProductOption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.ProductOption')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRelatedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('googleTaxonomy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypeAttribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=200)),
                ('show', models.CharField(max_length=255)),
                ('parentProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWholesalePricesArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('parentProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.Product')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('categoryId', models.IntegerField()),
                ('productCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeId', models.CharField(max_length=255)),
                ('storeUrl', models.URLField()),
                ('storeName', models.CharField(max_length=255)),
                ('invoiceLogoUrl', models.URLField()),
                ('emailLogoUrl', models.URLField()),
                ('starterSiteEcwidSubdomain', models.CharField(max_length=255)),
                ('starterSiteGeneratedUrl', models.URLField()),
                ('accountName', models.CharField(max_length=255)),
                ('accountNickName', models.CharField(max_length=255)),
                ('accountEmail', models.EmailField(max_length=254)),
                ('customerNotificationEmail', models.EmailField(max_length=254)),
                ('companyName', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('countryCode', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('stateOrProvinceCode', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('weightUnits', models.CharField(max_length=50)),
                ('handlingFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='productrelatedproducts',
            name='relatedCategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.RelatedCategory'),
        ),
        migrations.AddField(
            model_name='adminnotificationemail',
            name='storeInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victoriasJewlery.StoreInfo'),
        ),
    ]
